export default [
  {
    Name: "Soap",
    description: "Rose Soap",
    img: "",
    alt: "Image",
    price: "34",
    star: "5",
  },
  {
    Name: "Flour",
    description: "White Flour",
    img: "",
    alt: "Image",
    price: "20",
    star: "1",
  },
  {
    Name: "Biscuit",
    description: "Maliban Biscuit",
    img: "",
    alt: "Image",
    price: "60",
    star: "3",
  },
  {
    Name: "Curd",
    description: "Cow Mild curd",
    img: "",
    alt: "Image",
    price: "10.30",
    star: "2",
  },
  {
    Name: "Rice",
    description: "Sri Lankan Rice",
    img: "",
    alt: "Image",
    price: "60",
    star: "3",
  },
  {
    Name: "Milk",
    description: "cow milk",
    img: "",
    alt: "Image",
    price: "34",
    star: "3",
  },
];
